### PR TITLE
Sumeru Digital Branch

### PR DESCRIPTION
**Pull request by bharath653**
completed requirements

### CODE REVIEW

**Comment by bharath653** [comment]
added media query in header

**Comment by Dustin-Chromedome** [comment]
Please resolve the following merge conflicts:

package-lock.json
package.json
src/App.tsx
src/index.html
src/main.jsx
tsconfig.json
webpack.config.js

**Comment by bharath653** [comment]
Hi I just saw you have created a different branch sumeru, and this conflict is coming from main branch, so do you want me to fix this merge conflict in the main branch itself by trying to sync the project or push in the sumeru branch.

**Comment by Dustin-Chromedome** [comment]
> Hi I just saw you have created a different branch sumeru, and this conflict is coming from main branch, so do you want me to fix this merge conflict in the main branch itself by trying to sync the project or push in the sumeru branch.

Yes, please push to the Sumeru branch going forward.

**Pull request closed without merging**
